name: svelte
version: 0.0.4
description: Bindings of the Svelte library for building interactive interfaces.
homepage: https://github.com/Playform/svelte-dart
repository: https://github.com/Playform/svelte-dart
issue_tracker: https://github.com/Playform/svelte-dart/issues
environment:
    sdk: ">=2.0.0 <3.0.0"
